import { GymfitCheckInType, GymfitCheckInState } from "@curefit/gymfit-common";
export const GFCheckIn = [
  {
    id: "56741",
    userId: "yash",
    membershipId: "string",
    centerOfferingId: "string",
    eventId: 10,
    event: {
      id: 3,
      baseEventId: 4,
      fromTimeUTC: 1000,
      toTimeUTC: 1200,
      isActive: true,
      usedCapacity: 10,
    },
    checkInType: GymfitCheckInType.COMPLIMENTARY,
    state: GymfitCheckInState.VALIDATED,
    startTime: 1000,
    endTime: 1100,
    passCode: "30930",
  },
  {
    id: "56741",
    userId: "yash",
    membershipId: "string",
    centerOfferingId: "string",
    eventId: 10,
    event: {
      id: 3,
      baseEventId: 4,
      fromTimeUTC: 1000,
      toTimeUTC: 1200,
      isActive: true,
      usedCapacity: 10,
    },
    checkInType: GymfitCheckInType.COMPLIMENTARY,
    state: GymfitCheckInState.VALIDATED,
    startTime: 1000,
    endTime: 1100,
    passCode: "30930",
  },
  {
    id: "56741",
    userId: "yash",
    membershipId: "string",
    centerOfferingId: "string",
    eventId: 10,
    event: {
      id: 3,
      baseEventId: 4,
      fromTimeUTC: 1000,
      toTimeUTC: 1200,
      isActive: true,
      usedCapacity: 10,
    },
    checkInType: GymfitCheckInType.COMPLIMENTARY,
    state: GymfitCheckInState.VALIDATED,
    startTime: 1000,
    endTime: 1100,
    passCode: "30930",
  },
];
